export interface Event {
  id: string;
  title: string;
  description: string;
  location: string;
  summary: string;
  startDate: string;
  endDate: string;
  responseDeadline: string;
  minParticipants: number;
  maxParticipants: number;
  numberOfGuestsAllowed: number;
  requireResponse: boolean;
  attendenceCount: number;
  isSocial: boolean;
  ownerName: string;
}

export const getEvents = async (): Promise<Event[]> => {
  await new Promise((resolve) =>
    setTimeout(resolve, 2000 + Math.random() * 3000)
  );
  return simpleGetEvents();
};

export const simpleGetEvents = (): Event[] => [
  {
    id: "0ba28b2a-ab1c-4071-86bb-569ea595b203",
    title: "Språkkveld 💬🌍",
    description:
      "<p>Nå tenker du kanskje Java, C# eller Python, men denne kvelden skal det snakkes, ikke skrives eller kodes. Her får du mulighet til å friske opp skolekunnskap, forberede deg på sydenferie eller teste hvor godt Duolingo virkelig er.&nbsp;</p>\n<p></p>\n<p>Vi møtes i kantina, tar en matbit og så finner du deg et bord markert med  språket du ønsker å snakke . Vi sørger for at det er noen ved bordet som har et godt nivå på språket, og dersom det er behov, deler vi opp grupper etter ulike nivå. For tiden kan vi tilby fransk, spansk og tysk.</p>\n<p><strong>Har du lyst å snakke et annet språk, gi lyd! </strong>Det er ingen begrensninger; vil du snakke norsk, engelsk eller noe helt annet, setter vi gjerne opp flere grupper, uansett hvilket nivå du har.&nbsp;</p>\n<p></p>\n<p>Etter påmeldingen legger vi deg til Slack-kanalen «#øst-språkkafé» for å få en oversikt hvor mange vi er på hvert språk.</p>\n<p></p>\n<p>For alle som ikke er i Oslo, eller ikke har anledning å delta fysisk: vi kan få til <strong>digitale grupper </strong>også! Her kan vi for tiden tilby fransk og italiensk med kollegaer på andre kontorer. Vennligst noter i påmeldingen at du deltar digitalt.&nbsp;&nbsp;&nbsp;</p>\n<p></p>\n<p>Obs! Sluttid er et estimat. Det er lov å dra tidligere eller fortsette lengre, om man ønsker.</p>\n<p></p>\n<p>Velkommen! Bienvenue! Bienvenidos! Willkommen! Bienvenuti!</p>\n",
    location:
      '{"label":"Bouvethuset, Sørkedalsveien 8, Oslo, ","value":"10.711509,59.930495"}',
    summary: "",
    startDate: "2023-04-20T14:30:00Z",
    endDate: "2023-04-20T16:30:00Z",
    responseDeadline: "2023-04-19T08:30:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 8,
    isSocial: false,
    ownerName: "Maret Petersson",
  },
  {
    id: "1adead04-5f50-434d-babb-b2c3d3aa83ae",
    title: "Brettspillkveld",
    description:
      '<p>Ny runde med brettspill. Det er åpent for alle å delta. Hvilket eller hvilke spill som spilles, blir valgt av deltakerne når vi møtes, og hvor lenge utover kvelden du kan være med avgjør du selv. Det er alltid noen som tar med spill, og regler vil bli gjennomgått ved behov. Vi har også noen spill på Bouvethuset.</p>\n<p>Spørsmål kan stilles og informasjon finnes på Slack kanalen #øst-brettspill. Informasjon om spill finnes på <a href="https://boardgamegeek.com/browse/boardgame" target="_self">Boardgamegeek</a>.</p>\n<p>Skriv gjerne i kommentarfeltet eller meld fra på Slack (#øst-brettspill) hvilke spill du tar med eller har lyst til å spille.</p>\n<p>Alle endringer vedrørende din deltagelse gjøres her <a href="https://event.bouvet.no/" target="_self">https://event.bouvet.no/</a>.</p>\n<p>Informasjon om møterom og ev. pizza blir annonsert på Slack.</p>\n',
    location:
      '{"label":"Bouvethuset, Sørkedalsveien 8, Oslo, ","value":"10.711509,59.930495"}',
    summary: "",
    startDate: "2023-04-18T14:30:00Z",
    endDate: "2023-04-18T20:00:00Z",
    responseDeadline: "2023-04-18T10:00:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 6,
    isSocial: true,
    ownerName: "Gunnar Gjøen",
  },
  {
    id: "338e1408-3a30-4512-951d-dc22e081c5bf",
    title: "Løpetrening før Holmenkollstafetten 2",
    description:
      "<p>I forbindelse med årets Holmenkollstafett arrangerer vi tre løpetreninger med Ingrid Kristiansen - tidligere friidrettsutøver og langdistanseløper, som i andre halvdel av 1980-årene var blant verdens fremste. Treningene er forbeholdt de som skal delta på stafetten. Oppmøte er ved Sinnataggen i Frognerparken.</p>\n<p></p>\n<p>Info fra Ingrid:</p>\n<p>På kursdagen vil dere lære effektiv og riktig løpsteknikk, samtidig som dere lærer treningsprinsippene for å bli en bedre løper. I samme omgang får dere en intervalltrening på hver treningsdag.</p>\n<p>Kursdag 2:</p>\n<p>Vi løper på forskjellig underlag som flatt og bakker.</p>\n<p>Vi ser på øvelser/drills som får oss til å mestre den nye teknikken. Her er det viktig at vi ikke forandrer så mye på den naturlige teknikken til den enkelte slik at en kan løpe på seg nye små skader.</p>\n<p>Vi terper på løping i forskjellig terreng:</p>\n<p>1. Slak motbakke</p>\n<p>2. Flat mark</p>\n<p>3. Bratt motbakke</p>\n<p>4. Ser på hvordan overkroppen bør være for den enkelte for å få god fremdrift.</p>\n",
    location:
      '{"label":"Frognerparken, Kirkeveien, Oslo, ","value":"10.70195375,59.926667875"}',
    summary: "",
    startDate: "2023-05-03T14:30:00Z",
    endDate: "2023-05-03T15:45:00Z",
    responseDeadline: "2023-05-01T20:00:00Z",
    minParticipants: 5,
    maxParticipants: 19,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 19,
    isSocial: true,
    ownerName: "Ane Sofie Kristiansen",
  },
  {
    id: "388c5219-bf29-4fea-a40f-3f4bfd3121e0",
    title: "Fagtime testing i frontend",
    description: "<p>Mer informasjon kommer</p>\n",
    location:
      '{"label":"Bouvethuset, Sørkedalsveien 8, Oslo, ","value":"10.711509,59.930495"}',
    summary: "",
    startDate: "2023-04-28T11:00:00Z",
    endDate: "2023-04-28T12:00:00Z",
    responseDeadline: "2023-04-28T11:00:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 3,
    isSocial: false,
    ownerName: "Simen Norderud Jensen",
  },
  {
    id: "4b2cb1e8-44c2-4935-9550-c5b71afd29bd",
    title: "🔒 Sikkerhet på nett - Fagkveld 3 - Mobil som angrepsvektor",
    description:
      '<p>Faggruppen for sikkerhet inviterer til vårens fagserie! 🔒🌼</p>\n<p></p>\n<p>Temaet for fagserien er "Sikkerhet på nett", og vil ta for seg ulike temaer for hvordan øke sin personlige sikkerhet. Foredragene passer for alle, uansett hvor mye du kan om sikkerhet fra før av!</p>\n<p></p>\n<p>På tredje og siste fagkveld får vi besøk fra Telia, som skal dele om sine erfaringer og innsikt i trusselbildet knyttet til mobil og telefoni. De har planlagt et spennende foredrag om temaer som spoofing, SIM-jacking for social engineering og 2-faktor angrep.</p>\n<p></p>\n<p>Det blir enkel mat og drikke for de som deltar fysisk, men det vil også være mulig å følge med via Teams! 🕺🏼</p>\n<p>Foredraget varer 30-45 minutter, etterfulgt av mat og mingling.</p>\n<p></p>\n<p>Teamslenke:</p>\n<p></p>\n',
    location: '{"value":"","label":"Gruve 7, 2. etg, Bouvethuset Oslo"}',
    summary: "",
    startDate: "2023-04-18T13:00:00Z",
    endDate: "2023-04-18T14:30:00Z",
    responseDeadline: "2023-04-17T10:00:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 4,
    isSocial: false,
    ownerName: "Camilla Johannessen",
  },
  {
    id: "758d12a4-cf0e-444b-91a9-3d97c2cde901",
    title: "Sykveld på Labben ✂️",
    description:
      "<p><strong>Sykveld på labben</strong>! ✂️🕺🏼💃🏾</p>\n<p>Juhuu! Ta med deg et prosjekt, eller en idé til noe du ønsker å sette i gang med. Kanskje er du gira på å teste den nye broderingsmaskinen...? Eller du har aldri sydd før? Null problem, det vil være folk der som kan hjelpe deg i gang :)&nbsp;</p>\n<p></p>\n<p>Husk melde deg av om du ikke kommer - vi bestiller mat :)&nbsp;</p>\n",
    location: '{"value":"","label":""}',
    summary: "",
    startDate: "2023-03-21T15:00:00Z",
    endDate: "2023-03-21T19:00:00Z",
    responseDeadline: "2023-03-20T14:00:00Z",
    minParticipants: 0,
    maxParticipants: 12,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 6,
    isSocial: true,
    ownerName: "Silje Totland",
  },
  {
    id: "76d75035-3260-4ace-92bc-783749150ce8",
    title: "Bedriftsyoga 🧘🏻‍♀️",
    description:
      "<p>Hei!</p>\n<p>På Bouvethuset får vi ukentlig besøk av en yogainstruktør som holder timer i yogaformen Vinyasa for oss, som er en dynamisk yoga som passer like godt for nybegynnere som viderekomne!</p>\n<p></p>\n<p>Dette er en av morgentimene som holdes tirsdager kl. 07.30-08.30 i <strong>alle partallsuker.</strong></p>\n<p></p>\n<p>Alle er velkomne, og alt du trenger er en yogamatte! Bli med og få en god start på arbeidsdagen sammen med oss ☀️</p>\n",
    location:
      '{"value":"","label":"Kantina, Bouvethuset, Sørkedalsveien 8, Oslo"}',
    summary: "",
    startDate: "2023-04-18T05:30:00Z",
    endDate: "2023-04-18T06:30:00Z",
    responseDeadline: "2023-04-18T05:30:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 1,
    isSocial: false,
    ownerName: "Miriam Størseth Lillebo",
  },
  {
    id: "831e6e0c-c046-480b-9f35-5b376f6f5aab",
    title: "Bedriftsyoga 🧘🏻‍♀️",
    description:
      "<p><strong>NB: Denne uka er den vanlige ettermiddagstimen onsdag endret til en morgentime tirsdag!!</strong></p>\n<p></p>\n<p>På Bouvethuset får vi ukentlig besøk av en yogainstruktør som holder timer i yogaformen Vinyasa for oss, som er en dynamisk yoga som passer like godt for nybegynnere som viderekomne!</p>\n<p></p>\n<p>Alle er velkomne, og alt du trenger er en yogamatte! Bli med og få en god start på arbeidsdagen sammen med oss ☀️</p>\n",
    location:
      '{"value":"","label":"Kantina, Bouvethuset, Sørkedalsveien 8, Oslo"}',
    summary: "",
    startDate: "2023-03-28T05:30:00Z",
    endDate: "2023-03-28T06:30:00Z",
    responseDeadline: "2023-03-28T05:30:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 2,
    isSocial: false,
    ownerName: "Miriam Størseth Lillebo",
  },
  {
    id: "83d5295a-cd52-4aab-8903-e5719e4e3b86",
    title: "Stitur til Urørt i Alvdal",
    description:
      "<p>Årets stitur går til Urørt i Alvdal.&nbsp;</p>\n<p></p>\n<p>Alvdal er mer kjent for Kjell Aukrust sin bygd, men visste du at de har glimrende stisykling?&nbsp;</p>\n<p>Urørt setter opp ett opplegg som inkluderer overnatting, alle måltider og guider.&nbsp;</p>\n<p></p>\n<p>For de som er nybegynnere, eller aldri har syklet på sti så skal det også være ett opplegg med introduksjon til stisykling før man drar på tur. Det er viktig at alle får mestringsopplevelser i løpet av turen.&nbsp;</p>\n<p></p>\n<p>Det vil være mulighet for å leie elsykkel og vanlig fulldempet</p>\n<p></p>\n<p>Prisen for turen er 1500,-.</p>\n<p><strong>Inkludert i prisen</strong></p>\n<ul>\n<li>Overnatting</li>\n<li>Mat og drikke</li>\n<li>Shuttling</li>\n<li>Guiding</li>\n<li>Intro-kurs for nybegynnere</li>\n</ul>\n<p>Pris for el-sykkel: 640 per dag</p>\n<p>Pris for analog sykkel: 490 per dag</p>\n<p></p>\n<p>Vil du vite mer om Urørt og Alvdal?&nbsp;</p>\n<p>https://www.terrengsykkel.no/stisykling/sykling-alvdal/ta-med-stisykkelen-til-alvdal?userToken=228ab70e-747a-4255-b381-03798a6539e2</p>\n<p></p>\n<p>https://www.terrengsykkel.no/stisykling/sykling-alvdal/et-stopp-med-stisykkel-i-alvdal?userToken=73e9f4bf-1321-4521-b6e3-ba37e15f94f7</p>\n<p></p>\n",
    location: '{"label":"Alvdal, Innlandet","value":"10.630007,62.109939"}',
    summary: "",
    startDate: "2023-06-16T12:00:00Z",
    endDate: "2023-06-18T16:00:00Z",
    responseDeadline: "2023-05-02T14:00:00Z",
    minParticipants: 0,
    maxParticipants: 20,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 20,
    isSocial: true,
    ownerName: "Johannes Dvorak Lagos",
  },
  {
    id: "85f71a31-6861-4fb1-8cbe-f43290c02fc9",
    title: "Bedriftsyoga 🧘🏻‍♀️",
    description:
      "<p>Hei!</p>\n<p>På Bouvethuset får vi ukentlig besøk av en yogainstruktør som holder timer i yogaformen Vinyasa for oss, som er en dynamisk yoga som passer like godt for nybegynnere som viderekomne!</p>\n<p></p>\n<p>Dette er en av ettermiddagstimene som holdes onsdager kl. 16.30-17.30 i <strong>alle oddetallsuker.</strong></p>\n<p></p>\n<p>Alle er velkomne, og alt du trenger er en yogamatte! Bli med og få en god avslutning på arbeidsdagen sammen med oss ☀️</p>\n",
    location:
      '{"value":"","label":"Kantina, Bouvethuset, Sørkedalsveien 8, Oslo"}',
    summary: "",
    startDate: "2023-04-12T14:30:00Z",
    endDate: "2023-04-12T15:30:00Z",
    responseDeadline: "2023-04-12T14:30:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 1,
    isSocial: false,
    ownerName: "Miriam Størseth Lillebo",
  },
  {
    id: "8bde234d-10f3-4a25-a0f8-847d6ecfdd92",
    title: "#INNSEILING: Fortøyningsfest ⛵🕺 💃",
    description:
      "<p><em>OBS! Dette arrangementet er kun for medlemmer av Innseiling.</em></p>\n<p></p>\n<p>Fortøyningsfesten er festen der våre mest erfarne innseilere går planken ut av Innseilingsprogrammet. Alle i innseiling er selvfølgelig invitert til deres siste fest!&nbsp;</p>\n<p></p>\n<p>Mer info kommer!</p>\n",
    location: '{"value":"","label":"TBD"}',
    summary: "",
    startDate: "2023-06-09T14:00:00Z",
    endDate: "2023-06-09T20:00:00Z",
    responseDeadline: "2023-05-26T14:00:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 35,
    isSocial: true,
    ownerName: "Emilie Nyhus Fleischer",
  },
  {
    id: "8e6902a1-59c6-414e-8ab4-673d748eec54",
    title: "BouvetNxtOne",
    description:
      '<p><strong>Oppdatering:</strong></p>\n<p><em>(tidligere oppstartstidspunkt var feil)</em></p>\n<p><strong>Vi starter klokken 16:00 i Colosseum kino. </strong>Dørene åpner kl. 15:30 og enkel mat+drikke er tilgjengelig.</p>\n<p></p>\n<p>Du finner mer informasjon om arrangementet her:</p>\n<p><a href="https://minside.bouvet.no/ost/nyheter/velkommen-til-bouvetone-23-mars-2023" target="_self">https://minside.bouvet.no/ost/nyheter/velkommen-til-bouvetone-23-mars-2023</a></p>\n',
    location:
      '{"label":"Bouvethuset, Sørkedalsveien 8, Oslo, ","value":"10.711509,59.930495"}',
    summary: "",
    startDate: "2023-03-23T15:00:00Z",
    endDate: "2023-03-23T22:00:00Z",
    responseDeadline: "2023-03-15T22:00:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 439,
    isSocial: false,
    ownerName: "Ingvild Ilebekk",
  },
  {
    id: "93056ccd-c1be-495e-9a93-2018ad65f66f",
    title: "DS-tur: Norefjell 🎿💆‍♀️💆‍♂️❄☃",
    description:
      '<p><strong>Velkommen til årets DS-tur! ❄</strong>&nbsp;</p>\n<p></p>\n<p>I år snører vi vår sekk, spenner våre ski og vender snuten mot Norefjell ⛷🏔❄ Helgen 25.-26. mars har vi booket inn DS på Norefjell Ski og spa, der både eventyrlystne og uredde så vel som kosedyr kan finne glede og velvære 💆‍♀️💆‍♂️</p>\n<p></p>\n<p>Informasjon om hotellet finner dere <a href="https://norefjellskiogspa.no/" target="_self">her</a>.</p>\n<p></p>\n<p>Mer info om selve turen kommer!</p>\n',
    location: '{"value":"","label":"Norefjell Ski og spa"}',
    summary: "",
    startDate: "2023-03-25T12:00:00Z",
    endDate: "2023-03-26T14:00:00Z",
    responseDeadline: "2023-01-31T15:00:00Z",
    minParticipants: 0,
    maxParticipants: 50,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 33,
    isSocial: false,
    ownerName: "Kaja L. Solberg",
  },
  {
    id: "96a7f62f-b6fb-462d-a67d-45f86a352aa5",
    title: "Løpetrening før Holmenkollstafetten 1",
    description:
      "<p>I forbindelse med årets Holmenkollstafett arrangerer vi tre løpetreninger med Ingrid Kristiansen - tidligere friidrettsutøver og langdistanseløper, som i andre halvdel av 1980-årene var blant verdens fremste. Treningene er forbeholdt de som skal delta på stafetten. Oppmøte er ved Sinnataggen i Frognerparken. </p>\n<p></p>\n<p>Info fra Ingrid: </p>\n<p>På kursdagen vil dere lære effektiv og riktig løpsteknikk, samtidig som dere lærer treningsprinsippene for å bli en bedre løper. I samme omgang får dere en intervalltrening på hver treningsdag. </p>\n<p>Kursdag 1:</p>\n<p>Etter oppvarming og litt drills, kjører vi en lett intervallbetont trening, slik at dere får en god</p>\n<p>treningsøkt ved siden av teknikktrening.</p>\n<p>* Jeg viser dere god/riktig/effektiv løpeteknikk.</p>\n<p>* Dere får prøve – og jeg gir den enkelte tilbakemelding.</p>\n<p>* Dere får individuelle oppgaver å jobbe med.</p>\n",
    location:
      '{"label":"Frognerparken, Kirkeveien, Oslo, ","value":"10.70195375,59.926667875"}',
    summary: "",
    startDate: "2023-04-26T14:30:00Z",
    endDate: "2023-04-26T15:45:00Z",
    responseDeadline: "2023-04-24T20:00:00Z",
    minParticipants: 5,
    maxParticipants: 19,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 19,
    isSocial: true,
    ownerName: "Ane Sofie Kristiansen",
  },
  {
    id: "994000ac-f596-4102-b8a8-cd8db65ce262",
    title:
      "Åpen fagkveld: Parallellprogrammering med Rust (Fearless concurrency)",
    description:
      '<p>30. mars arrangerer vi Tech2s andre eksterne meetup, denne gangen om Rust! 👏🎉 Meld deg gjerne på via Meetup også så vi får en felles oversikt: <a href="https://www.meetup.com/bouvet-deler/events/291954077/" target="_self">https://www.meetup.com/bouvet-deler/events/291954077/</a></p>\n<p>&nbsp;</p>\n<p>For å optimalisere ytelsen av moderne prosessorer kan programmer benytte parallell oppførsel. Dessverre medfører dette ny kompleksitet og til tider ubehagelige bugs.</p>\n<p></p>\n<p>Rust er designet for å skrive programmer med ytelsen til C, men uten minnefeil. Måten Rust unngår minnefeil, The Borrow Checker, eliminerer også mange mulige feil ved parallelle programmer. Dette gjør Rust unikt egnet for å skrive programmer med parallell oppførsel.</p>\n<p></p>\n<p>I dette foredraget skal Alexander Michael Staff sammenligne parallelle programmer skrevet i Rust, C# og C++ for å utforske hvilket språk som har best ergonomi, og hvilket som gir best ytelse.</p>\n<p></p>\n<p><strong>Agenda:</strong><br>17:00: Oppmøte og pizza<br>17:30: Velkommen!<br>17:35: Parallellprogrammering med Rust: Fearless concurrency<br>18:30: Spørsmål, diskusjon og mingling<br>19:00: Avslutning</p>\n<p></p>\n',
    location: '{"value":"","label":"Herregårdskroa, 3. etg, Bouvethuset Oslo"}',
    summary: "",
    startDate: "2023-03-30T15:00:00Z",
    endDate: "2023-03-30T17:00:00Z",
    responseDeadline: "2023-03-27T15:00:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 7,
    isSocial: false,
    ownerName: "Maren Parnas Gulnes",
  },
  {
    id: "9b65552f-7c23-4570-b02e-527d7d04ec62",
    title: "Labbaften",
    description:
      '<p>Kom innom for å jobbe på ditt eget prosjekt, hjelpe andre eller bare for å være sosial! <a href="https://bouvet.slack.com/archives/C38JRNVPV" target="_self">#labben-oslo</a> er stedet du kan få hjelp med ditt hobbyprosjekt, finne på Norges neste revolusjonerende oppfinnelse, få hjelp til reparasjon, reparere ting i fikserassen, spille Nintendo eller bare prate med kollegaer!</p>\n<p>Vi har hammer, symaskin, 3D printere, mikrokontrollere, sensorer, loddebolter og mye mer! 😊</p>\n<p>Velkommen!</p>\n',
    location: "",
    summary: "",
    startDate: "2023-04-26T14:00:00Z",
    endDate: "2023-04-26T19:00:00Z",
    responseDeadline: "2023-04-26T14:00:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 100,
    requireResponse: false,
    attendenceCount: 9,
    isSocial: false,
    ownerName: "Jesper Andersson",
  },
  {
    id: "9d393c72-28b7-420c-9824-46928938eeaa",
    title: "Bedriftsyoga 🧘🏻‍♀️",
    description:
      "<p>Hei!</p>\n<p>På Bouvethuset får vi ukentlig besøk av en yogainstruktør som holder timer i yogaformen Vinyasa for oss, som er en dynamisk yoga som passer like godt for nybegynnere som viderekomne!</p>\n<p></p>\n<p>Dette er en av morgentimene som holdes tirsdager kl. 07.30-08.30 i <strong>alle partallsuker.</strong></p>\n<p></p>\n<p>Alle er velkomne, og alt du trenger er en yogamatte! Bli med og få en god start på arbeidsdagen sammen med oss ☀️</p>\n",
    location:
      '{"value":"","label":"Kantina, Bouvethuset, Sørkedalsveien 8, Oslo"}',
    summary: "",
    startDate: "2023-04-26T14:30:00Z",
    endDate: "2023-04-26T15:30:00Z",
    responseDeadline: "2023-04-26T14:30:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 1,
    isSocial: false,
    ownerName: "Miriam Størseth Lillebo",
  },
  {
    id: "a5356c23-09e5-411d-8b25-767d9ab6cfcc",
    title: "#INNSEILING: Påskerebus - Egglekene 2023 🥚 🐥",
    description:
      "<p><em>OBS! Dette arrangementet er kun for medlemmer av Innseiling.</em></p>\n<p></p>\n<p>Vårens mest spennende jakt! Meld deg på og hold av datoen 📅 Mer info kommer!</p>\n",
    location: '{"value":"","label":"TBD"}',
    summary: "",
    startDate: "2023-04-14T14:00:00Z",
    endDate: "2023-04-14T19:00:00Z",
    responseDeadline: "2023-04-05T14:00:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 26,
    isSocial: true,
    ownerName: "Emilie Nyhus Fleischer",
  },
  {
    id: "adff1c08-b8c3-4179-b896-990f415bf3b8",
    title: "Bedriftsyoga 🧘🏻‍♀️",
    description:
      "<p>Hei!</p>\n<p>På Bouvethuset får vi ukentlig besøk av en yogainstruktør som holder timer i yogaformen Vinyasa for oss, som er en dynamisk yoga som passer like godt for nybegynnere som viderekomne!</p>\n<p></p>\n<p>Dette er en av morgentimene som holdes tirsdager kl. 07.30-08.30 i <strong>alle partallsuker.</strong></p>\n<p></p>\n<p>Alle er velkomne, og alt du trenger er en yogamatte! Bli med og få en god start på arbeidsdagen sammen med oss ☀️</p>\n",
    location:
      '{"value":"","label":"Kantina, Bouvethuset, Sørkedalsveien 8, Oslo"}',
    summary: "",
    startDate: "2023-05-02T05:30:00Z",
    endDate: "2023-05-02T06:30:00Z",
    responseDeadline: "2023-05-02T05:30:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 1,
    isSocial: false,
    ownerName: "Miriam Størseth Lillebo",
  },
  {
    id: "b69c79d2-a839-42b3-9b24-57882705b49f",
    title: "#INNSEILING: Konsulenthistorier 🕮",
    description:
      "<p><em>OBS! Dette arrangementet er kun for medlemmer av Innseiling.</em></p>\n<p></p>\n<p>Hva opplever man egentlig som konsulent ute hos kunde? Mer info om arrangementet kommer!</p>\n",
    location:
      '{"label":"Bouvethuset, Sørkedalsveien 8, Oslo, ","value":"10.711509,59.930495"}',
    summary: "",
    startDate: "2023-04-25T15:00:00Z",
    endDate: "2023-04-25T18:00:00Z",
    responseDeadline: "2023-04-24T10:00:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 22,
    isSocial: false,
    ownerName: "Emilie Nyhus Fleischer",
  },
  {
    id: "ca62a8e7-f7b1-4294-9520-ecac366f7b01",
    title: "🔸Working title: Kodekveld",
    description:
      "<p>Er du en sånn raring som liker å kode på fritida også? Syns du det er kjedelig å kode alene? Er det for lite pizza i livet ditt?</p>\n<p></p>\n<p><strong>Introduserer felles fritid-kode-kveld på Bouvethuset!</strong></p>\n<p></p>\n<p>Her er tanken at du kan sitte å jobbe med hva du vil sammen med kolleager du kanskje ikke ser så mye av til vanlig. En ypperlig mulighet til å gjøre 2023 til året der du faktisk fullfører et eneste kodeprosjekt!</p>\n<p></p>\n<p>Det blir sikkert noe snaks, så meld dere på så vet jeg sånn sirka hvor mye som trengs.</p>\n",
    location: '{"value":"","label":"Bouvethuset 4 etg"}',
    summary: "",
    startDate: "2023-04-19T14:00:00Z",
    endDate: "2023-04-19T19:00:00Z",
    responseDeadline: "2023-04-19T14:00:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 8,
    isSocial: false,
    ownerName: "Jesper Andersson",
  },
  {
    id: "e00ac5da-a229-45eb-8ff9-63fc0f1088d5",
    title: "Bedriftsyoga 🧘🏻‍♀️",
    description:
      "<p>Hei!</p>\n<p>På Bouvethuset får vi ukentlig besøk av en yogainstruktør som holder timer i yogaformen Vinyasa for oss, som er en dynamisk yoga som passer like godt for nybegynnere som viderekomne!</p>\n<p>Dette er en av morgentimene som holdes tirsdager kl. 07.30-08.30 i <strong>alle partallsuker.</strong></p>\n<p>Alle er velkomne, og alt du trenger er en yogamatte! Bli med og få en god start på arbeidsdagen sammen med oss ☀️</p>\n",
    location:
      '{"value":"","label":"Kantina, Bouvethuset, Sørkedalsveien 8, Oslo"}',
    summary: "",
    startDate: "2023-03-21T06:30:00Z",
    endDate: "2023-03-21T07:30:00Z",
    responseDeadline: "2023-03-21T06:30:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 7,
    isSocial: false,
    ownerName: "Miriam Størseth Lillebo",
  },
  {
    id: "e0707e00-6888-42c2-8f81-42163110f7f5",
    title: "Løpetrening før Holmenkollstafetten 3",
    description:
      "<p>I forbindelse med årets Holmenkollstafett arrangerer vi tre løpetreninger med Ingrid Kristiansen - tidligere friidrettsutøver og langdistanseløper, som i andre halvdel av 1980-årene var blant verdens fremste. Treningene er forbeholdt de som skal delta på stafetten. Oppmøte er ved Sinnataggen i Frognerparken.</p>\n<p></p>\n<p>Info fra Ingrid:</p>\n<p>På kursdagen vil dere lære effektiv og riktig løpsteknikk, samtidig som dere lærer treningsprinsippene for å bli en bedre løper. I samme omgang får dere en intervalltrening på hver treningsdag.</p>\n<p>Kursdag 3:</p>\n<p>Jeg vil legge opp til en</p>\n<p>treningsøkt (intervallprinsippet, slik at alle kan føle at de mestrer denne treninga)</p>\n<p>I dag vil jeg sette fokus på :</p>\n<p>1. Løpe mest mulig på forfot (dersom leggene til kursdeltakerne er sterke nok)</p>\n<p>2. Få hofta frem, slik at du ikke henger bakpå.</p>\n<p>3. Løpe i litt større fart litt over tid slik at alle «skavankene» kan komme frem. Den enkelte får god tilbakemelding på sitt nivå.</p>\n",
    location:
      '{"label":"Frognerparken, Kirkeveien, Oslo, ","value":"10.70195375,59.926667875"}',
    summary: "",
    startDate: "2023-05-10T14:30:00Z",
    endDate: "2023-05-10T15:45:00Z",
    responseDeadline: "2023-05-08T20:00:00Z",
    minParticipants: 5,
    maxParticipants: 19,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 19,
    isSocial: true,
    ownerName: "Ane Sofie Kristiansen",
  },
  {
    id: "e8746439-1cd9-479e-b3ed-db81256c4e6c",
    title: "Golftur 2023",
    description:
      '<p>Hei alle samme</p>\n<p></p>\n<p>Bouvet Øst Golf inviterer til golftur til Halmstad/Tylebäck i Sverige fredag <strong>28.april til mandag 1. mai.</strong></p>\n<p>Dette er en tur for alle, med hovedfokus er på det sosiale.</p>\n<p></p>\n<p>Vi har bedt om golf-pakke på <a href="https://tyleback.se/" target="_self">Tylebäck</a>, noen få meter fra <a href="https://www.hgk.se/" target="_self">Halmstad Golfklubb</a>, som har 2 fantastiske baner:</p>\n<ul>\n<li>Overnatting fredag til mandag m/frokost</li>\n<li>Greenfee x 3</li>\n</ul>\n<p>Bouvet sponer med 2500kr, som utgjør overnatting. Greenfee og mat må betales av den enkelte.</p>\n<p></p>\n<p>Høres det interessant ut? Meld deg på da vel. Dette blir en hyggelig opplevelse.</p>\n<p></p>\n<p></p>\n<p><strong>Oppdatering 14. mars:</strong></p>\n<p>Golf-pakke fra Tylebäck inneholder følgende:</p>\n<ul>\n<li>Logi del i dubbelrum</li>\n<li>3 dygns logi</li>\n<li>3 frukostbuffé</li>\n<li>1 greenfee lördag Halmstad GK norra</li>\n<li>1 greenfee söndag Halmstad GK södra</li>\n<li>1 greenfee måndag Halmstad GK norra</li>\n</ul>\n<p>Pris: 5 144 kr per person, hvor Bouvet dekker nesten halvparten.</p>\n<p></p>\n<p>Det er også mulig å bestille 2-retters middag for 365 kr (krever forholdsbestilling).</p>\n<p></p>\n<p></p>\n<p>Turkomiten,</p>\n<p>Jhon, Philip og Ole</p>\n<p></p>\n<p></p>\n',
    location: '{"value":"","label":"Halmstad i Sverige"}',
    summary: "",
    startDate: "2023-04-28T14:00:00Z",
    endDate: "2023-05-01T14:00:00Z",
    responseDeadline: "2023-03-27T14:00:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 6,
    isSocial: true,
    ownerName: "Ole Fjetland",
  },
  {
    id: "eaf18aa1-84c8-43bb-81a6-f67abdb96032",
    title: "Holmenkollstafetten 2023",
    description:
      "<p>Påmeldingen til årets vakreste eventyr <strong>Holmenkollstafetten</strong> <strong>lørdag</strong> <strong>13. mai 2023 </strong>er nå åpen!</p>\n<p>Bouvet har en lang tradisjon med deltakelse, og her er alle nivåer velkomne. Distansene varierer mellom 370 og 2840 meter, altså noe for enhver smak.<br>Vi har som mål å stille med 4 lag (15 pers per lag), og trenger også noen som kan være reserver.&nbsp;</p>\n<p>Etter løpet samles vi til bankett med en god middag og feirer den gode innsatsen.</p>\n<p>Dette er et veldig hyggelig, men først og fremst sosialt arrangement. Enten du ønsker å teste konkurranseinstiktet eller bare vil nyte løypa uten tidspress, vil vi ha med akkurat deg!</p>\n",
    location: '{"label":"Oslo","value":"10.7389701,59.9133301"}',
    summary: "",
    startDate: "2023-05-13T10:00:00Z",
    endDate: "2023-05-13T21:00:00Z",
    responseDeadline: "2023-03-31T10:00:00Z",
    minParticipants: 0,
    maxParticipants: 74,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 75,
    isSocial: true,
    ownerName: "Ellen Nøstvik Bakksjø",
  },
  {
    id: "eb9c52b7-e812-45af-a244-49a6b0fd9230",
    title: "🔒 Sikkerhet på nett - Fagkveld 2 - LastPass vs. Keeper",
    description:
      '<p>Faggruppen for sikkerhet inviterer til vårens fagserie! 🔒🌼</p>\n<p></p>\n<p>Temaet for fagserien er "Sikkerhet på nett", og vil ta for seg ulike temaer for hvordan øke sin personlige sikkerhet. Foredragene passer for alle, uansett hvor mye du kan om sikkerhet fra før av!</p>\n<p></p>\n<p>På andre fagkveld er vi så heldige at IT skal fortelle om prosessen bak bytte av passordbank i Bouvet. Hva gjorde at vi ikke lenger ønsket å bruke LastPass? Hvilke kriterier var viktige i valg av ny løsning for passordbank? Hvorfor falt valget på Keeper?</p>\n<p></p>\n<p>❗️Det viktig å påpeke at dette er ikke et forum for hverken support eller å dele sine personlige meninger om valget som er blitt gjort. Vi forventer at alle forholder seg konstruktive og hyggelige ☺️</p>\n<p></p>\n<p>Det blir enkel mat og drikke for de som deltar fysisk, men det vil også være mulig å følge med via Teams! 🕺🏼</p>\n<p>Foredraget varer ca. 30 minutter, etterfulgt av mat og mingling.</p>\n<p></p>\n<p>Teamslenke:</p>\n<p></p>\n',
    location:
      '{"value":"","label":"Hog in the Pound - 3. etg, Bouvethuset Oslo"}',
    summary: "",
    startDate: "2023-03-28T13:30:00Z",
    endDate: "2023-03-28T14:30:00Z",
    responseDeadline: "2023-03-27T10:00:00Z",
    minParticipants: 0,
    maxParticipants: 0,
    numberOfGuestsAllowed: 0,
    requireResponse: false,
    attendenceCount: 3,
    isSocial: false,
    ownerName: "Camilla Johannessen",
  },
];
